### ISSUE TITLE
Hides title bar on popup style windows

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [poehlerj/no-title-bar#7] opened 2020-02-10 22:10 UTC
Makes moving and closing popup style windows quite interesting:

![image](https://user-images.githubusercontent.com/1327332/74194979-3812b200-4c52-11ea-957c-8459e4543865.png)

Any idea if the windows have types and if maximisation is not possible then keep showing the titlebar?

Other than this small issue, great extension and thanks for maintaining a fork!

**Comment by poehlerj** [comment] 2020-02-11 17:11
Hello @Caffe1neAdd1ct,
this definitely looks somehow broken. Can you give me some detail, what environment you are using? X.Org or Wayland and which gnome version? 
Also: does this only happen on specific popups or on all of them? I have been using the Jetbrains products a lot in the past and cannot really remember ever experiencing such problem.

**Comment by Caffe1neAdd1ct** [comment] 2020-02-14 15:29
I'll dig some details out when i'm at that machine again, X.Org most likely as Wayland has some issues to iron out when running games and nvidia drivers.

Noticed on all popups in Java based applications (netbeans/dbeaver/phpstorm), i'll test some native gnome applications and get back on this one.

**Comment by Caffe1neAdd1ct** [comment] 2020-02-14 21:50
So environment:

Arch Linux
Gnome 3.34.2
X.Org - Wayland disabled 

Also removes the titlebar off minecraft when in window mode and not maximised so seems very Java based.

Gedit -> preferences popup is fine (gnome based apps appear fine)

![image](https://user-images.githubusercontent.com/1327332/74570151-f6487b00-4f73-11ea-9031-dceb574108b0.png)

Screenshot showing netbeans/minecraft/gedit+popup

**Comment by jdohm** [comment] 2020-05-02 00:35
got the same problem (with Flameshot - which is written in javascript). Interestingly using the old "no title bar" + "Gtk title bar" does not have this issue.

Environment: 
Ubuntu 20.04
Gnome 3.36.1
X.Org 1.20.8 - with X11

**Comment by poehlerj** [comment] 2020-05-14 15:44
I was finally able to reproduce this and then rewrote a big part of the (un-)decoration code. This should be fixed with the next update, coming up (it is already in review)

**Comment by Caffe1neAdd1ct** [comment] 2020-05-14 15:46
@poehlerj You're an absolute star, i'll test asap :+1:

**Comment by poehlerj** [comment] 2020-11-23 15:55
Assuming that this issue is resolved by now, since I didn't here anything different and haven't experienced similar in the past couple of months. If anything comes up again, just reopen this issue.

**Closed as completed by poehlerj** 2020-11-23 15:55 UTC
